package com.drrufus.lab1server.service;

import com.drrufus.autogenerated.User;
import com.drrufus.lab1server.dao.UserDao;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class UserService {
    
    @Autowired
    private UserDao userDao;
    
    public User getUserById(int id) {
        return userDao.getUserById(id);
    }
    
    public List<User> getUserByParams(Integer id, String login, String name, String email, String pass) throws Exception {
        return userDao.getUserByParams(id, login, name, email, pass);
    }
    
    public int createUser(String login, String name, String email, String pass) throws Exception {
        return userDao.insertUser(login, name, email, pass);
    }
    
    public void modifyUser(Integer id, String login, String name, String email, String pass) throws Exception {
        userDao.modifyUser(id, login, name, email, pass);
    }
    
    public void deleteUser(Integer id) {
        userDao.deleteUser(id);
    }
}
